package = "luacomgen-utils"
version = "0.1-1"
source = {
	url = "..." -- We don't have one yet
}
description = {
	summary = "Utilitary functions to use interfaces generated by LuaComGen.",
	homepage = "https://github.com/mascarenhas/luacomgen/",
	license = "MIT/X11",
}
dependencies = {
	"lua >= 5.2, < 5.4"
}
build = {
	type = "builtin",
	modules = {
		comgen = {
			sources = { "comgen.cpp" },
			libraries = { "user32", "ole32" },
		},
	}
}
